apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: fnh7l3o96-go
  janus-idp.io/tekton: fnh7l3o96-go
  backstage.io/kubernetes-id: fnh7l3o96-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: fnh7l3o96-go
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
