apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: fnh7l3o96-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: fnh7l3o96-go 
  name: fnh7l3o96-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: fnh7l3o96-go 
